apiVersion: batch/v1
kind: CronJob
metadata:
  name: batch-job-after-5-minutes
spec:
  schedule: '01 17 * * *'
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: periodic-batch-job
        spec:
          restartPolicy: OnFailure
          containers:
            - name: main
              image: luksa/batch-job
